# Generated by Django 4.2.28 on 2026-02-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
