# Generated by Django 4.2.28 on 2026-02-15 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Appartement', '0002_apartment_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='Douala', max_length=255),
        ),
        migrations.AddField(
            model_name='apartment',
            name='country',
            field=models.CharField(default='cameroun', max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
