# Generated by Django 4.2.28 on 2026-02-15 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Appartement', '0003_apartment_city_apartment_country_alter_apartment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentunavailable',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
